// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bgHeight': string;
  'birdHeight': string;
  'birdWidth': string;
  'pipeHeight': string;
  'pipeWidth': string;
  'scaleMultiplier': string;
  'windowDistanceMultiplier': string;
}
export const cssExports: CssExports;
export default cssExports;
